Allow SCID to match the next packet
martinthomson/train-protocol pull request #16
Opened 2024-08-20 07:00 UTC by martinthomson

Closes #13.

2024-08-20 13:59 UTC, huitema approved these changes

2024-08-21 01:05 UTC, huitema requested changes
We need to also update the text in section 5.2. Processing TRAIN Packets. Current text says "A TRAIN packet MUST be discarded, along with any packets that come after it in the same datagram, if the Source Connection ID Length is non-zero."

The correct text ought to be something like:

"A TRAIN packet MUST be discarded, along with any packets that come after it in the same datagram, if the Source Connection ID is not consistent with the coalesced packets, as
specified in {{packet}}."

2024-08-21 02:24 UTC, martinthomson commented
Good catch.  Though I realize now, when writing this up, that this is not necessarily possible.

Let's say that you process packets in order.  The order of events is something like this:

1. You process the TRAIN packet.  It looks fine, but you can't validate the SCID yet.  You save the indicated rate for later.
2. You process the v1 packet that follows.  It is fine and you handle it.
3. You now go back to the indicated rate and apply it.

At what point do you recognize that the SCID in the TRAIN packet is bad?  You _could_, I guess, interrupt the processing of the v1 packet at the point that you read off the SCID and abort the entire thing.  That might be possible in our implementation, though it is a little bit weird because it requires acting on state that might not be saved otherwise.  But it's a bit intrusive and I can't see how that would be easy to do in a general fashion.

I'm going to go with "MAY" for the requirement, because I can't see how this would be reliably implemented without a whole lot of back and forth.  The harm here is minimal, so if it isn't enforced, that's OK as long as the packet is well-formed.

2024-08-21 04:01 UTC, huitema approved these changes

2024-08-21 04:20 UTC, kazuho approved these changes

2024-08-21 07:51 UTC, merged